# Generated by Django 2.2.3 on 2019-07-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=230)),
                ('roll_No', models.IntegerField()),
                ('gender', models.CharField(choices=[('g', 'gender'), ('f', 'female'), ('u', 'undisclosed')], max_length=1)),
            ],
        ),
    ]
