# Generated by Django 2.2 on 2019-05-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='articles',
            field=models.ManyToManyField(to='main.Article'),
        ),
    ]
