# Generated by Django 2.2 on 2019-05-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_author_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='articles',
        ),
    ]
